### ISSUE TITLE
epic(api): Endpoint for Entity History Retrieval

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#19]
### Task Description

Implement API endpoint that allows  retrieval of the history of a specific enties.

The history should be retrievable with a new History Resolver for each of the components. The returned value should be an list of the history entities, that do not include the possibility to retrieve again the history. 

We are utilizing MariaDBs Version Tables "https://mariadb.com/kb/en/system-versioned-tables/".

Dependency
Heureka Authentication, Epic: #7 

### Acceptance Criteria:

- [ ] history sub resolver returns list of history entries for the entity
- [ ] on db access layer the history is fetched with an separate function
- [ ] on app layer the decision is taken whatever the query on db layer is performed or not 
- [ ] history entries are ordered by time
- [ ] allow also time span history retrival

### Expected Tests:

- [ ] reasonable e2e tests 
- [ ] reasonable db layer tests
- [ ] reasonable app layer tests

### Note
Create tickets for each entity or entity group.

**Comment by lolaapenna** [comment]
Notes from David:

> Special SQL queries should be used that show historical data based on table versions
> we have basically a feature within MariaDB which are versioned tables for this purpose
