### ISSUE TITLE
chore(codeGenerate): Remove Generated Code and Replace with "Generation through Makefile"

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#190]
**Task Description**

We use a lot of generated code across the project. As the generation is entirely reproducible we should avoid checking in the generated code and rather generate the code on demand. 
This includes the need to generate the code in container builds and deployments.

**Acceptance Criteria:**
- [ ] All generated Code is removed from repository 
- [ ] Add single command to make that re-generates everything 
- [ ] Add generation of code during image builds 
- [ ] Add generation of code during github actions

**Expected Test:**
- [ ] Manual testing of above

**Comment by lolaapenna** [comment]
We may not remove generated code because it includes implementation.
