### ISSUE TITLE
epic(entitymod): Heureka Entity Modelling

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#2]
Definition of the core entities (data objects), the relationships between them, and how the data structure will be exposed through the API.

Acceptance Requirement:
- [x] Define a clear and consistent representation of data throughout the API. 
- [x] Enable flexibility to allow for future expansion (possible addition of new entities or relationships without significantly impacting existing functionalities.)
- [x] Documentation of the entities and entity relationships clearly outlining the data structure and available operations.
