### ISSUE TITLE
epic(multi-cluster-scan): Enable Multiple Clusters for the Scanners

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#207]
### Description

The scanners currently scan a single cluster, we need to onboard all clusters to the scanners to ensure comprehensive infrastructure coverage.

### Objectives

- Work on the Deployment of Scanners to multiple clusters
- Investigate further potential errors occurring on additional data sets
- Maintain or improve the performance and accuracy of the scanners based on new data sets

### Tasks
- [x] Enable the Kubernetes Scanner for all clusters
- [x] Enable the Image Scanner for all clusters
- [x] Enable scanner Logs to be available for investigation

### Acceptance Criteria

- Kubernetes Scanner is enabled and running on multiple clusters
- Image Scanner is enabled and running on multiple clusters
- Scanner Logs are available for investigation
- Scans occur at least daily
- Heureka db partially wiped daily to ensure remediated issues disappear (workaround)

**Comment by lolaapenna** [comment]
Image scanner (Keppel) is currently deployed on only EUDE1 because images in EU-DE-1 are mirrored in other clusters.
We need to confirm if we have exceptions to this behavior.

Deployment has been done for all scale-out cluster + (normal) clusters. We also need to conform if we need to do same for admin clusters.
