### ISSUE TITLE
epic(OS_Scan): Conduct Design Sessions for Implementation of OpenStack Compliance Scan

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#223]
### Description

This epic focuses on conducting design sessions to plan and strategize the implementation of OpenStack Compliance Scans.

### Objective
To develop a comprehensive and effective approach to ensure that the OpenStack environment meets all compliance requirements as outlined in the [SAP Converged Cloud - Security Hardening](https://wiki.one.int.sap/wiki/display/itsec/SAP+Converged+Cloud+-+Security+Hardening) policy. These sessions will involve key stakeholders and subject matter experts to design the Heureka compliance scan framework collaboratively.

### Tasks
- [ ] Review Compliance Requirements:
- [ ] Decide on Tooling for Scanners
- [ ] Decide on the first scanner scope
> Scanners (Assets)?
>    - [ ] VM Scanner
>    - [ ] Virtual Network Scanner
>    - [ ] Security Group Scanner
>    - [ ] VM Image Scanner

> Scanners (Policy)?
>    - [ ] Invalid Security Group configuration ?!

**Future Decision to be made**
- [ ] Design RBAC Implementation:
  - Define roles, permissions, and access levels.
- [ ] Decide how to handle Nested Resources:
  - Develop strategies for handling nested resources, including project IDs, embedded services, user attributes, and support groups.
