### ISSUE TITLE
epic(cont-scan): Implement Continuous Scans for the Scanners

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#224]
### Description

This epic focuses on enhancing the scanners to support continuous scanning capabilities.

### Objectives

To equip the scanners with the ability to detect changes since the last scan and update results accordingly, eliminating the need to wipe results from each scan.

### Tasks

- [x] Add tracking of Scan Jobs
- [x] Add scanner registration capabilities
- [ ] Adjust scanners to do authenticated queries and submit their Job Status
- [ ] Add trigger for automatic closure of remediated issues
- [ ] E2E Tests for Scan Tracking
- [ ] E2E Tests for Scanner Registration
- [ ] Integration Tests for Automatic Closure
