### ISSUE TITLE
epic(activity): Activity Management

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#23]
### Description

This epic focuses on implementing an Activity Management system to track the progress of each discovered security issue.

### Objectives

Each identified issue will be assigned to a unique 'Activity,' allowing for detailed tracking of remediation or mitigation actions. 

### Tasks
- [ ] Design Activity Management Framework
- [ ] Implement Detailed Activity Log
- [ ] Design User Interface
- [ ] Test and Validate

### Acceptance Criteria:
-  Automatically generate a detailed activity log for each identified security issue upon successful matching with a component.

- The activity log shall capture relevant details for each issue, including:
   - Relevant dates
   - Issue severity
   - Affected component information, etc

- The user interface shall provide a dedicated view for accessing and managing individual activity
