### ISSUE TITLE
feat(scan-job): implement job tracking

### ISSUE THREAD

**Issue by drochow** [cloudoperators/heureka#237]
**Task Description**

We need to track scan/data collection jobs and their scope definitions to remediate issues once they are resolved automatically. Therefore, job tracking must be implemented to store the job's status and definition of scope. 

We furthermore make the following assumptions: 

- A job is only complete when it reports that back
- A job of a specific scope does always collect the same "information" when the state of the information does not change
    -  therefore, items that do not appear can be handled after finishing the Job as 
- Overlapping scan scopes may occur 

Relevant Entities: 

- User 
- Component
- Component Instance
- Issue Match 
- Component Version 

**Acceptance Criteria:**

- [ ] When a new scan starts, it should be able to insert a new job by providing the following: 
    - a scope definition (plain string, decided by scanner)
    - (the start date is implicitly assumed to be the submission time)
- [ ] When a scan finishes, it should be able to update an existing job by providing the following: 
   -  ID of the Job
   -  state (success)
- [ ] When a scan fails, it should be able to update an existing job by providing the following: 
   -  ID of the Job
   -  state ( failure )
   -  context (free text/JSON)
- [ ] The scanner identity is derived from the JWT token (token-based authentication) and is attached to the Job. 
- [ ] It's not possible to update the Job of another identity 
- [ ] It's not possible to remove the Job of another identity from an entity 
- [ ] It is possible to add a job to an existing component that is already attached to another job
- [ ] All entities need to be able to get attached to a Job during creation and update
    - [ ] GraphQL Mutations for adding a job to each entity do exist
    - [ ] GraphQL Mutations for removing a job from each entity do exist
    - [ ] Respective App Layer functionality exists for each entity
    - [ ] Respective Data Access Layer functionality exists for each entity
    - [ ] Respective, composite indexed cross tables do exist
- [ ] All added App Layer  entries need to emit respective events using the event handler

**Expected Test:**

**E2E**
- Starting a Job (happy case)
- Finish a Job (happy case)
- Starting multiple jobs without finishing/reporting failure from the same identity should fail 
- Starting a job, finishing it, and starting then another job should work (happy case)
- Report Failure of a Job (Happy case)
- Finish a Job of another Identity should not work
- Report Failure of a Job of another Identity should not work
- Adding a job to an entity (for each entity) (happy case)
- Removing a job from an entity ( for each entity) (happy case) 
- Adding a non-existent job to an entity should fail (for each entity) 
- Removing a non-existent job to an entity should fail (for each entity) 
- Adding a non-existent job to an entity should fail (for each entity) 
- Removing a job that is not your identity should fail (for each entity) 

**App Layer**
- Happy Case Unit tests similar to E2E
- Error Cases similar to above, and ensure:
   - Check that we emit specific errors for wrong identity test cases
   - Check that we emit specific errors for not existing job test cases
   - Check that we emit specific errors for not existing entity test cases 
   - Check that we emit specific errors for double job running cases

**Database**
- Happy Case Unit Tests for all Inserts/Updates
- Edge Case Unit Tests for all Inserts/Updates

Dependencies
- #344

**Comment by lolaapenna** [comment]
Scanner protocol is in place.
