### ISSUE TITLE
feat(jobFilters): Implement Filtering for Jobs 

### ISSUE THREAD

**Issue by drochow** [cloudoperators/heureka#238]
**Task Description**
Based on #237, we need to filter the respective relevant entities by jobs and jobs by entities. 

Relevant entities are:
- User
- Component
- Component Instance
- Issue Match
- Component Version

**Acceptance Criteria:**

- [ ] Existing GraphQL Queries are adjusted to allow filtering by JobID
- [ ] Existing Filters on the App Layer allow filtering by JobID
- [ ] Job Filter allows filtering for respective entity IDs for relevant entities
- Database Access Layer: 
    - [ ] Existing List functionalities include filtering by job id
    - [ ] Job Filtering supports all entities
    - [ ] The join is only built when the respective filter is used
- [ ] You can search by multiple job IDs at once (entity filtering)
- [ ] You can search based on multiple entities at once (job filtering)
- [ ] It is possible to list jobs for each of the entities using GraphQL
     - [ ] For respective entities, resolvers need to be created that allow fetching from the respective parent.
     - example:  
```graphql
query ($filter: UserFilter, $first: Int, $after: String) {
    Users (
        filter: $filter,
        first: $first,
        after: $after
    ) {
        totalCount
        edges {
            node {
                id
                name
                jobs { # <----- Direct connection via the UserResolver -> JobsResolver
                  edges { 
                      node { 
                           id
                          status
                        } 
                  }
                }
            }
            cursor
        }
    }
}
```
     - [ ] The established Base Resolver pattern is used

**Expected Test:**

Across Layers:
- Happy case tests for existing entries
- Tests for a massive list of jobs
- tests for non-existing entries

Dependencies
- #344
