### ISSUE TITLE
feat(authentication): implement OIDC authentication

### ISSUE THREAD

**Issue by MR2011** [cloudoperators/heureka#239]
**Task Description**

Currently we only provide Token Based Authentication for API access. In order to provide a seamless login experience we want to implement OpenID Connect (OIDC) authentication in our application for users.

**Acceptance Criteria:**

- [ ] Oidc Url and Oidc Client Id can be provided via config file
- [ ] Authentication handler verifies token when API accessed
- [ ] User can authenticate with valid id token
- [ ] User can't use API without valid id token

**Expected Test:**

E2E
- [] trying to access with valid id token
- [] trying to access with invalid id token

**Comment by michalkrzyz** [comment]
`package authentication

import (
	"context"
	"fmt"

	"github.com/coreos/go-oidc"
	log "github.com/sirupsen/logrus"
)

var (
	Verifier *oidc.IDTokenVerifier
)

type IDTokenClaims struct {
	Sub           string `json:"sub"`
	EmailVerified bool   `json:"email_verified"`
	Mail          string `json:"mail"`
	Iss           string `json:"iss"`
	LastName      string `json:"last_name"`
	GivenName     string `json:"access_token"`
	Aud           string `json:"aud"`
	UserUuid      string `json:"user_uuid"`
	Exp           int    `json:"exp"`
	IAT           int    `json:"iat"`
	FirstName     string `json:"first_name"`
	FamilyName    string `json:"family_name"`
	JTI           string `json:"jti"`
	Email         string `json:"email"`
}

func Verify(rawIDToken string) (*oidc.IDToken, error) {
	token, err := Verifier.Verify(context.TODO(), rawIDToken)
	if err != nil {
		return nil, fmt.Errorf("verifier error: %v", err)
	}
	return token, nil
}

func Init(providerURL string, clientID string) error {
	provider, err := oidc.NewProvider(context.TODO(), providerURL)
	if err != nil {
		return fmt.Errorf("OIDC provider init error: %v", err)
	}

	oidcConfig := &oidc.Config{
		ClientID: clientID,
	}
	Verifier = provider.Verifier(oidcConfig)

	log.WithField("module", "oidc-verifier").Info("OIDC verifier initialized")
	return nil
}`

**Comment by michalkrzyz** [comment]
- oidc auth is the middleware for user authentication to access API
- oidc auth barer will be checked in http header: "Authorization: Barer <OIDC_token>"
- oidc token will be set in variable AUTH_OIDC_TOKEN
- existing token auth middleware (JWT) is the method to authenticate scanner to access API
- JWT token will be checked in http header: "X-Service-Authorization: Barer <JWT_Token>
- JWT token secret will be set in variable AUTH_TOKEN_SECRET
- both methods will be enabled when AUTH_ENABLE=true

**Comment by michalkrzyz** [comment]
there is another option to use oidc/jwt config instead of AUTH_ENABLE:
* When AUTH_OIDC_URL is set Then OIDC auth will be checked
* When AUTH_TOKEN_SECRET is set Then JWT token will be checked
* When AUTH_OIDC_URL is set and AUTH_TOKEN_SECRET is not then only OIDC will be an option to authenticate
* When AUTH_TOKEN_SECRET is set and AUTH_OIDC_URL is not set then only JWT token will be an option to authenticate
* When neither AUTH_OIDC_URL and AUTH_TOKEN_SECRET is defined, then no authentication is required to access API

**Comment by lolaapenna** [comment]
This will be split into 2 issues by @michalkrzyz

**Comment by MR2011** [comment]
Draft PR created, open for review

**Comment by michalkrzyz** [comment]
I have closed previous PR as it had some issues. I will set up new one on Monday (some testing left on todo list). It will have full, e2e proven, oidc flow without redirection (token is created offline). We will need to rethink redirection implementation. What do we need to support (single client_id or many etc).
