### ISSUE TITLE
epic(activity): Remediation Tracking

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#24]
### Description

This epic focuses on implementing a comprehensive remediation tracking system to monitor and manage the state changes of issue matches.

### Objectives

Heureka Activity will allow the ability to manage the remediation process for each security issue. 
Users can document specific actions taken, track status (in progress, Mitigated, Accepted, Irrelevant, etc), and optionally associate other relevant details such as timestamps and responsible users with each remediation step.

### Tasks
- [ ] Design Remediation Tracking Framework
- [ ] Implement Progress Tracking
- [ ] Test and Validate
