### ISSUE TITLE
chore(ui): review graphql queries

### ISSUE THREAD

**Issue by MR2011** [cloudoperators/heureka#240]
**Task Description**

The GraphQL queries used in the[ UI ](https://github.com/cloudoperators/juno/tree/main/apps/heureka)fetch currently more data than is required. This might lead to performance issues. Additionally, we might want to use [Data Loaders](https://gqlgen.com/reference/dataloaders/) where it's necessary to make data fetching more efficient on the backend.

**Acceptance Criteria:**

- [ ] Remove unnecessary data request in UI queries
- [ ] Evaluate using Data loaders
- [ ] Implement Data loaders if required

**Expected Test:**

In case Data Loaders will be implemented, tests should verify that they work as intended.
