### ISSUE TITLE
chore(rn): add resourcename to additional entities

### ISSUE THREAD

**Issue by MR2011** [cloudoperators/heureka#241]
**Task Description**

A resource naming schema makes the identification easier. Therefore, it should be added to the following entities:

- Service
- Component
- Component Version
- Support Group

**Acceptance Criteria:**

- [ ] Replace `name` with `rn` in respective entity if it exists. Otherwise add `rn`
- [ ] Update existing GraphQL queries
- [ ] Update existing Test cases
- [ ] Update GraphQL queries in K8S-Scanner
- [ ] Update GraphQL queries in Keppel-Scanner
- [ ] Add `rn` to filter on db and api layer

**Expected Test:**
- Add new tests for filtering per `rn` if they don't exist

**Comment by lolaapenna** [comment]
We need to remove the CCRN.
