### ISSUE TITLE
research(OS_Scan):  Research on how to handle component version in policy violation based scanners

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#246]
**Task Description**

For the Open Stack Policy scan, we have the first policy violations instead of vulnerabilities and also new kinds of components. This comes with the question of whether the same schema needs/should be applied. 

Currently, we do have components that can have multiple versions and those versions can have instances: 

```mermaid
erDiagram
    ComponentInstance       }o--|| ComponentVersion: "is an instance of" 
    ComponentVersion        }|--|| Component: "is a version of"
```

For an OpenStack Entity such as a Security Group the question now arises if we want to store and represent data in a similar format. 

Possible options could be: 

- Do not use components and component versions and create component instances/issue matches directly
- Do use the same schema but enhance component versions with context information, and use a hash sum of the context as a version identifier
- Other...

**Acceptance Criteria:**

- [x] Have decision drivers worked out
- [x] ADR created with multiple options evaluated
- [ ] Informed decision taken

**Comment by lolaapenna** [comment]
A meeting will be scheduled to sync further (David, Michael and Max).

**Comment by lolaapenna** [comment]
pending @drochow  review
