### ISSUE TITLE
fix(scanner): Investigate bugs on large scale scans

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#247]
**Task Description**
The first iteration of scanners for scanning for vulnerabilities on Kubernetes, Assets, and CVEs from NVD has been implemented. However, during scanning on a larger scale, we encountered a lot of errors.

Therefore we need to investigate those errors and fix them.

**Acceptance Criteria:**

- [x] Scanners run on large-scale environments without errors
- [x] Data from Scans is at least partially checked for correctness and completeness
- [x] Address Performance issues during scanning 

**Expected Test:**

- Where it does make sense, add regression tests. Use common sense
