### ISSUE TITLE
epic(activity): Evidence Management

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#25]
### Description

This epic focuses on implementing an Evidence Management system within the Heureka Activity framework.

### Objectives

To provide a means for compliance evidence fulfillment, allowing users to add and modify evidence while ensuring all changes remain transparent and visible. This will enhance the ability to track and manage compliance-related documentation associated with individual security issues.

### Tasks
- [ ] Conduct user interviews to figure out specific needs e.g bulk fixes
- [ ] Design Evidence Management Framework
- [ ] Implement Evidence Upload and Association Mechanism
- [ ] Design User Interface
- [ ] Test and Validate

### Acceptance Criteria:
- The activity feature shall provide a dedicated section for uploading and associating compliance evidence with individual security issues.
- Added evidences shall be securely stored and linked to the corresponding security issue activity.
