### ISSUE TITLE
refactor(error): Implement Error Interfaces

### ISSUE THREAD

**Issue by MR2011** [cloudoperators/heureka#253]
**Task Description**

Currently Heureka does not have proper error handling. A good starting point would be to define some possible errors such as `DuplicatedEntry` per Layer and return these.

**Acceptance Criteria:**

- [ ] Errors defined on database layer
- [ ] New errors returned by database layer
- [ ] Errors defined on app layer
- [ ] New errors returned by app layer
- [ ] Errors defined on api layer
- [ ] New errors returned by api layer

**Expected Test:**
No further tests required

**Comment by lolaapenna** [comment]
This will moved to BL
