### ISSUE TITLE
chore(doc): Update Documents

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#255]
**Task Description**
Update all documents to reflect the current state of Heureka in a simplified, easy-to-understand manner. This includes the README and the product design document.

**Acceptance Criteria:**
- [x] Descriptions should be free of ambiguous terms and statements.
- [x] Use cases describing possible scenarios should be included.
- [x] Use simple and easy-to-understand language.
