### ISSUE TITLE
refactor(issueMatch): fulltextSearch performance 

### ISSUE THREAD

**Issue by drochow** [cloudoperators/heureka#259]
**Task Description**

The wildcard search option for issue matches (searching for the issue's primary name and issue variant's secondary name ) turns out not to be performant enough for the expected size of tables. 

Therefore, as an intermediate solution, we want to add fulltext indexes to the respective fields and adjust the wildcard search to only support wildcards at the end of the search term.

Reference: https://mariadb.com/kb/en/full-text-index-overview/

**Acceptance Criteria:**

- [ ] Relevant fields have FULLTEXT index added
- [ ] the wildcard search is implemented with the match syntax
- [ ] respective tests are performed

**Expected Test:**
- Performance tests
- existing functional tests should keep working
