### ISSUE TITLE
refactor(service): allow wildcards in service search 

### ISSUE THREAD

**Issue by drochow** [cloudoperators/heureka#260]
**Task Description**

The service search term does currently append a wildcard at start and end. Parse the string instead and replace "*" with wildcards. 

**Acceptance Criteria:**

- [ ] Wildcards can get dynamically be added 
- [ ] Multiple wildcards are possible
- [ ] Providing NO wildcard does result in an exact term search

**Expected Test:**
- Existing tests should break, as functionality changes
- Add tests for:
    -  multiple wildcards
    - single wildcards
    - exact term
