### ISSUE TITLE
fix(eventRegistry): unblock api requests

### ISSUE THREAD

**Issue by drochow** [cloudoperators/heureka#261]
**Task Description**

The event registry currently works with Go channels. When the channel buffer is full, the registry can not add new events until a job clears the buffer. 

This, especially with higher backpressure, leads to blocking io behavior of the API. 

We need to fix this by changing the design. We also need to assume that the application may crash in between, events may be lost, or we may run out of memory.

**Acceptance Criteria:**

- [ ] event registry should use another mechanism to store events
- [ ] buffer should be cleared fast
- [ ] limit additional architectural complexity

**Expected Test:**

- [ ] add high backpressure test

**Comment by drochow** [comment]
This implicitly includes some research and a decision. 

Do we want to use a lightweight queue? Do we persist events simply in a table?

**Comment by drochow** [comment]
I personally would suggest to investigate https://nats.io/ for this purpose.

Other suggestions are welcome. @MR2011  @dorneanu
