### ISSUE TITLE
feat(issuematch):Enable data layer to get issue-variant via CI

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#270]
**Task Description**

The current implementation of the issue matching does not really work out its to many queries in a row instead of using a performant join. Therefore we need to implement the possibility to fetch issue variants of a component instance including their priority for the respective service

**Acceptance Criteria:**

- [ ] Should be a separated function for the data access layer
- [ ] The returned entity should include the priority of the respective issue variants
- [ ] Only issue variants that "match" the respective component instance should be returned 
- [ ] Have a separate filter and DO NOT re-use the existing issueVariant filter
- [ ] Add it to the implementation of the issue matching
- [ ] Needs to work without a existing issue match
- [ ] unit tests

**Expected Test:**

- Tests for issue matching event handler
- Tests for issue variant fetching on data access layer

**Comment by dorneanu** [comment]
I need some more context here (mainly to validate my thoughts).

**Comment by dorneanu** [comment]
This has already been implemented. Waiting for PR.
