### ISSUE TITLE
chore(Demo): Prepare for PoC Demo (21.10.2024)

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#288]
**Task Description**
We need to prepare for the upcoming Apeiro Showcase taking place next week on Monday (21.10).

**Acceptance Criteria:**
- [ ] Establish the scope
- [ ] Establish the content to be presented
- [ ] Mock Demo carried out

**Expected Test:**
Add any information about how this will be tested.

**Comment by drochow** [comment]
Demo done
