### ISSUE TITLE
epic(remediation): Requirement Gathering for Remediation Tracking

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#292]
### Description
Following the user interviews conducted during the workshop, user feedback on existing implementations as well as expectations regarding the remediation of issues will be translated to define requirements for the Remediation Management feature of Heureka.

### Objectives

- Understand common challenges: analyze the difficulties users experience with the current patch management process to inform feature development.
- Cluster user expectations: consolidate user suggestions for the remediation management feature of Heureka.
- Prioritize development efforts: assess and prioritize potential features and improvements based on the feedback and their anticipated impact on efficiency.
- Enhance UX: Improve the overall user experience by addressing pain points on the current state of Heureka.

### Tasks

- [x] PoC user test and feedback gathering
- [x] Conduct user interviews (include persona fit)
- [x] Conduct a detailed analysis of user interview data to identify key themes and challenges related to remediation management.
- [x] Break down the requirements into smaller, actionable tasks or user stories. 
- [x] Develop a prioritized roadmap for feature implementation based on user feedback and strategic goals.
- [x] Document all requirements clearly and concisely, ensuring they are actionable and measurable.
