### ISSUE TITLE
chore(sprintOrg): Conduct Sprint Retrospective/Planning Session-Sprint 11/24

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#294]
**Task Description**
To track and document the previous sprint review and the new sprint planning commitments.

---

#### Duration Sep 23 - Oct 20

**Planned Epics**

> 1. Implement Authentication
> 2. Implement Heureka Issue Matches
> 3. Implement Component Instances view
> 4. Implement interconnection of Heureka Core and Scanners
> 5. Onboard New Colleagues from SGS SDAI
> 6. Conduct Design Sessions for the Implementation of OpenStack Compliance Scan
> 7. Improve performance and UX after having real data

**Closed Epics:**

> -  Improve performance and UX after having real data
> - Implement Heureka Issue Matches
> - Onboard New Colleagues from SGS SDAI

**Touched Epics:**

> - Implement Authentication
> - Implement Component Instances view
> - Conduct Design Sessions for the Implementation of OpenStack Compliance Scan

**Untouched Epics**
> -  Implement interconnection of Heureka Core and Scanners

#### Availability:
- David - 2 days away, Dustin - 2 days away, Max - 2 days away

**Rolled-over Epics – Touched Epics from 9/24**

> - Implement Authentication
> - Conduct Design Sessions for the Implementation of OpenStack Compliance Scan

**Moved Epics – Untouched Epics from 9/24**
> -  None

**Planned Epics**

> - Implement Authentication
> - Conduct Design Sessions for the Implementation of OpenStack Compliance Scan 
> - Implement Continuous Scans for the Scanners
> - Post-PoC Performance Improvements
> - Address initial feedback from Heureka PoC demo

**Comment by lolaapenna** [comment]
**Apeiro sprint 10 items:**
- (heureka): Refined Heureka PoC: Solve the limitations of the PoC
- (heureka): Refined Heureka Issue Matcher: Enhance the Issue Matcher service

**Update on the items for Sprint 10 (adding as a comment)**
```
Several issues were discovered with the PoC. As a result, the planned epics for Sprint 11 have been paused to address these new tasks.

These tasks fall in 2 categories (epics):
- Fix performance issues and UX after having real data - Delayed loading of entities when handling real data.

- Fix Bugs with Heureka Issue Matches - Errors in service matching and support group matching.
```


**Apeiro sprint 11 items:**

```
**1. (heureka) Enable Multiple Clusters for the Scanners**
### Description
The scanners currently scan a single cluster, we need to onboard all clusters to the scanners to ensure comprehensive infrastructure coverage.

### Objectives
- Extend the scanner's capability to handle multiple clusters.
- Ensure seamless integration and scanning of all clusters.
- Maintain or improve the performance and accuracy of the scanners.

### Acceptance Criteria
Kubernetes Scanner is enabled for all clusters
Image Scanner is enabled for all clusters
```


```
**2. (heureka) Implement Continuous Scans for the Scanners**

### Description
This epic focuses on enhancing the scanners to support continuous scanning capabilities.

### Objectives
To equip the scanners with the ability to detect changes since the last scan and update results accordingly, eliminating the need to wipe results from each scan.

### Acceptance Criteria
Continuous Scanning Framework is designed
Incremental Updates is Implemented
Testing and Validation is done
```

```
**3. epic(demo): Address initial feedback from Heureka PoC demo**

### Description
The idea is to compile received feedback form demoing the PoC until until a formal feedback channel is established..

### Objectives
Ensure continuous improvement in parallel with ongoing development.

### Acceptance Criteria
- [ ] Implement sorting by Target Remediation Date, and Severity
- [ ] Implement filter for Severity != None - provide a filter option to exclude entries where Severity is None.
- [ ] Implement identification of Severity (None) on the Service Detail view - Entries with Severity set to None should be clearly identified in the Service Detail view.

```
