### ISSUE TITLE
epic(demo-feedback): Address initial feedback from Heureka PoC demo

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#295]
### Description

The idea is to compile received feedback form demoing the PoC until a formal feedback channel is established.

### Objectives
- Ensure continuous improvement in parallel with ongoing development.

### Tasks

- [x] Establish a formal feedback channel: document, consolidate, and link it to a created issue for resolution.

- [x] Sorting

- [x] Implement sorting by:
    - [ ] Issue Matches:   
#310 
         - [ ] by Target Remediation Date
         - [ ] by Severity
         - [ ] by Name

    - [ ] Service:
#377  
        - [ ] by Name

- [ ] Implement default filter selection for All Severities but None -->  filter for Severity != None

- [x] Implement identification of Severity (None) on the Service Detail view - Entries with Severity set to None should not be displayed as issues on the service detail view
#378 

- [x] Add Pagination for Component Instances in Service Detail View 
        https://github.com/cloudoperators/heureka/issues/337

- [x] Decide: Allow Filtering for Services & Support Group Name on the Issue Match Search or indicate that only searching for CVE's is supported
- [x] Implement initial filter
https://github.com/cloudoperators/heureka/issues/371
https://github.com/cloudoperators/heureka/issues/375
