### ISSUE TITLE
feat(issueMatch): Ordering and Pagination

### ISSUE THREAD

**Issue by drochow** [cloudoperators/heureka#310]
**Task Description**

Ordering is an essential feature for interacting with the Heureka UI. Especially ordering by "target remediation date", "Severity" and "Primay Name"  as well as "CCRN" for issue matches is requested.

It needs to be investigated if we want to allow ordering by arbitary number of fields. Depending on the effort that's may be enabled in a separate Issue.

**Acceptance Criteria:**

- [ ] You can order by Target Remediation Date
- [ ] You can order by Severity
- [ ] You can order by Primary Name 
- [ ] You can order by CCRN
- [ ] (MAY) You can order by an arbitrary combination of those
- [ ] A clean interface for ordering on the API layer is defined
- [ ] The API does provide information WHAT field can be ordered
- [ ] Its possible to order on both directions 

**Expected Test:**

- [ ] e2e test for ordering by 1 field (per enabled field)
- [ ] (may) e2e test for ordering by 2 fields
- [ ] e2e test for ordering by 3 fields
- [ ] integration tests for ordering on DB Access Layer

**Comment by lolaapenna** [comment]
The implementation approach may change after review.
