### ISSUE TITLE
epic(demo): Heureka Use case Demo

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#34]
The goal is to set the satge for showcasing how Heureka discovers issues, and provides the means for remediation progress tracking.

The planed use case will be for Vulnerability Issue Class.

- [x] - Define the scope for the Demo - Asset + Vulnerability Discovery - Backend Connectivity
- [x] - Define the storyline for the Demo - The Manager persona PoV
- [x] - Prepare the presentation deck - #192
