### ISSUE TITLE
chore(SprintOrg): Prepare for the upcoming Sprint

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#350]
**Task Description**
To organise all Apeiro and Heureka sprint activities

**Acceptance Criteria:**

- [x] Apeiro Backlog: Review committed epics for sprint 11
- [x] Apeiro Backlog: Outline stakeholder-understandable epics planned for Sprint 12
- [x] Apeiro Backlog: Review Apeiro  commitments in the next Heureka Core Meeting on 13th Nov.
- [x] Apeiro Backlog: Update Apeiro project board - Next Apeiro Monthly backlog meeting takes place on 15th Nov.
- [x] Heureka Backlog: Review committed epics for sprint 11
- [x] Heureka Backlog: Outline epics for sprint 12

**Comment by lolaapenna** [comment]
## Sprint 11/24 Retrospective
#### Duration Oct 21  - Nov 17

**Planned Epics**

> - Implement Authentication
> - Conduct Design Sessions for the Implementation of OpenStack Compliance Scan 
> - Implement Continuous Scans for the Scanners
> - Post-PoC Performance Improvements
> - Address initial feedback from Heureka PoC demo

**Closed Epics:**

> -  Implement Authentication
> - 

**Touched Epics:**

> - Conduct Design Sessions for the Implementation of OpenStack Compliance Scan 
> - Implement Continuous Scans for the Scanners
> - Post-PoC Performance Improvements
> - Address initial feedback from Heureka PoC demo

**Untouched Epics**
> -  ...
> - 

## Sprint 12/24 Planning
#### Duration Nov 18 - Dec 15

#### Availability:
- 

**Rolled-over Epics – Touched Epics from 9/24**

> - ...

**Moved Epics – Untouched Epics from 9/24**
> -  ...

**Planned Epics**

> - December Workshop (Req for Remediation Management + 2025 Roadmap)
