### ISSUE TITLE
feat(issueVariant): Allow for issue variant creation with just severity rating

### ISSUE THREAD

**Issue by BlakePatterson** [cloudoperators/heureka#361]
**Task Description**
Currently the severity input type for creating issue variants only accepts a cvss vector. Add a rating field alongside vector and update the resolver methods to allow for creating a new issue variant where vector is not provided. 

**Acceptance Criteria:**

- [x] Add a "rating" field of type SeverityValues to SeverityInput
- [x] Add a new "NewSeverityFromRating" function that creates a severity with only the rating field and not the vector
- [x] Add logic to handle between when a vector is provided and when only a rating is provided
- [x] Be able to create a new IssueVariant with only a rating

**Comment by lolaapenna** [comment]
Review comments have been added
