### ISSUE TITLE
feat(service): Ordering

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#377]
**Task Description**

Ordering is an essential feature for interacting with the Heureka UI. In addition to ordering issue matches, we need implement ordering services by service name.

**Acceptance Criteria:**

- [ ] You can order services by service name

**Expected Test:**

- [ ] e2e test for ordering by service name
- [ ] integration tests for ordering on DB Access Layer
