### ISSUE TITLE
feat(deployment): Deployment for K8s Assets Scanner

### ISSUE THREAD

**Issue by lolaapenna** [cloudoperators/heureka#389]
**Task Description**

Work on a deployment of the k8s asset scanner across multiple clusters and multiple regions. Perform the Deployment with the functioning component and ensure this way that the helm-chart and images published are useable in the checked-in state.

**Acceptance Criteria:**

- [ ] Use Helm Charts published in/by cloudoperators/heureka
- [ ] Use images published in/by cloudoperators/heureka
- [ ] Deployment should span multiple regions/clusters
- [ ] Fully functional deployed end state
